# NUMPY ARRAY OLUŞTURMA

######  import library

In [3]:
import numpy as np

######  Creating numpy array

In [4]:
np.array([1,2,3,4]) # creating numpy array

array([1, 2, 3, 4])

###### Creating numpy array with zeros

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###### Creating numpy array with ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

###### Creating numpy array with range

In [9]:
np.arange(10,50,5) # between 10 and 50 increasing 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.arange(0,2,0.2) # between 0 and 2 increasing 0.2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

###### Creating numpy array with equal range

In [12]:
np.linspace(0,4,12) # between 0 and 4 , 12 number with equal range

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

###### Creating numpy array with random numbers

In [13]:
np.random.rand(3,4) 

array([[0.22553366, 0.98599419, 0.9396721 , 0.48374058],
       [0.71693656, 0.61440353, 0.1550616 , 0.64273677],
       [0.82675516, 0.58704446, 0.66195473, 0.17869268]])

In [14]:
np.random.randn(2,5) # normal distribution form

array([[ 1.11342293,  1.1009645 ,  0.00421309,  0.91750747,  0.7089014 ],
       [ 1.16947941,  0.10345452,  1.26142829, -0.67369365,  0.50984459]])

In [16]:
np.random.randint(1,50,15)

array([43,  4, 18,  9, 43, 24,  6, 23, 19, 10, 38, 26,  9, 41, 49])

###### Creating numpy unit matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### Reshape numpy array

In [17]:
np.arange(28).reshape(4,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [38]:
a = np.arange(50)
a.shape = 2,5,-1   # defining automatically z axis column number with -1
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

###### Mathematical Operations

In [39]:
matrix = np.random.randint(0,100,28).reshape(4,7)
print("sum of elements: "+str(matrix.sum()))
print("max of elements: "+str(matrix.max())+" index of it :"+str(matrix.argmax()))
print("min of elements: "+str(matrix.min())+" index of it :"+str(matrix.argmin()))
matrix

sum of elements: 1486
max of elements: 97 index of it :26
min of elements: 0 index of it :6


array([[43, 59, 32,  2, 11, 80,  0],
       [93, 39, 73,  8, 35, 27, 47],
       [77, 42, 65, 64, 62, 52, 96],
       [34, 79,  0, 89, 94, 97, 86]])