In [1]:
import numpy as np

In [4]:
a = np.array([20,40,60,80])
b = np.arange(4)

### Adding Two Arrays 

In [5]:
a + b

array([20, 41, 62, 83])

In [7]:
a.reshape(2,2) + np.eye(2)

array([[21., 40.],
       [60., 81.]])

###### Statistical Operations 

In [67]:
b = np .arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [71]:
print("sum of all elements:"+str(b.sum()))
print("sum of row elements:"+str(b.sum(axis=1)))
print("sum of column elements:"+str(b.sum(axis=0)))
print("shape :"+str(b.shape))
print("median : "+str(np.median(b)))
print("standart deviation : "+str(np.std(b)))
print("variance : "+str(np.var(b)))
print("mean : "+str(b.mean()))
print("max of all elements  : "+str(b.max()))
print("max of row elements  : \n"+str(b.max(axis=1)))
print("min  : "+str(b.min()))
print("min of row elements  : \n"+str(b.min(axis=0)))
print("cumulatif sum of x axis : \n"+str(b.cumsum(axis=1))) # cumulatif sum of rows
print("cumulatif sum of y axis : \n"+str(b.cumsum(axis=0))) # cumulatif sum of columns
b > 50

sum of all elements:105
sum of row elements:[10 35 60]
sum of column elements:[15 18 21 24 27]
shape :(3, 5)
median : 7.0
standart deviation : 4.320493798938574
variance : 18.666666666666668
mean : 7.0
max of all elements  : 14
max of row elements  : 
[ 4  9 14]
min  : 0
min of row elements  : 
[0 1 2 3 4]
cumulatif sum of x axis : 
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]]
cumulatif sum of y axis : 
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

###### Copy an Array

In [53]:
copy = b.copy()

###### Unique Elements Selecting

In [54]:
cities = np.array(["ankara","istanbul","kayseri","ankara"])
np.unique(cities)

array(['ankara', 'istanbul', 'kayseri'], dtype='<U8')